# this is an FCOS pipeline
type: fcos

streams:
    master:
      type: production
      variants: []
      branch: master
      cosa_image: "coreos-assembler:main"
    "4.11":
      type: production
      branch: release-4.11
      cosa_image: "coreos-assembler:rhcos-4.11"
    "4.10":
      type: production
      branch: release-4.10
      cosa_image: "coreos-assembler:rhcos-4.10"
    "4.9":
      type: production
      branch: release-4.9
      cosa_image: "coreos-assembler:rhcos-4.9"
    "4.8":
      type: production
      branch: release-4.8
      cosa_image: "coreos-assembler:rhcos-4.8"
    "4.7":
      type: production
      branch: release-4.7
      cosa_image: "coreos-assembler:rhcos-4.7"
    "4.6":
      type: production
      branch: release-4.6
      cosa_image: "coreos-assembler:rhcos-4.6"

# additional_arches: [aarch64, ppc64le, s390x]
additional_arches: [ppc64le]

source_config:
  url: https://github.com/openshift/os

artifacts:
  aarch64:
    "4.8":
      bootimages:
        - AWS
        - Installer
        - Metal
    "4.9":
      bootimages:
        - AWS
        - Installer
        - Metal
        - OpenStack
    "4.10":
      bootimages:
        - AWS
        - Installer
        - Metal
        - OpenStack
    "4.11":
      bootimages:
        - AWS
        - Azure
        - Installer
        - Metal
        - OpenStack
    master:
      bootimages:
        - AWS
        - Azure
        - Installer
        - Metal
        - OpenStack
  ppc64le:
    "4.6":
      bootimages:
        - Installer
        - Metal
        - OpenStack
    "4.7":
      bootimages:
        - Installer
        - Metal
        - OpenStack
    "4.8":
      bootimages:
        - Installer
        - Metal
        - OpenStack
    "4.9":
      bootimages:
        - Installer
        - Metal
        - OpenStack
    "4.10":
      bootimages:
        - Installer
        - Metal
        - OpenStack
    "4.11":
      bootimages:
        - Installer
        - Metal
        - OpenStack
        - PowerVS
    master:
      bootimages:
        - Installer
        - Metal
        - OpenStack
        - PowerVs
  s390x:
    "4.6":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    "4.7":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    "4.8":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    "4.9":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    "4.10":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    "4.11":
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
    master:
      bootimages:
        - Dasd
        - Installer
        - Metal
        - OpenStack
  x86_64:
    "4.6":
      bootimages:
        - AWS
        - Azure
        - Installer
        - Metal
        - OpenStack
        - VMware
        - GCP
    "4.7":
      bootimages:
        - AWS
        - Azure
        - IBMCloud
        - Installer
        - Metal
        - OpenStack
        - VMware
        - GCP
    "4.8":
      bootimages:
        - AWS
        - Azure
        - IBMCloud
        - Installer
        - Metal
        - OpenStack
        - VMware
        - GCP
    "4.9":
      bootimages:
        - AWS
        - Azure
        - AzureStack
        - IBMCloud
        - Installer
        - Metal
        - OpenStack
        - VMware
        - GCP
    "4.10":
      bootimages:
        - Aliyun
        - AWS
        - Azure
        - AzureStack
        - IBMCloud
        - Installer
        - Metal
        - Nutanix
        - OpenStack
        - VMware
        - GCP
    "4.11":
      bootimages:
        - Aliyun
        - AWS
        - Azure
        - AzureStack
        - IBMCloud
        - Installer
        - Metal
        - Nutanix
        - OpenStack
        - VMware
        - GCP
    master:
      bootimages:
        - Aliyun
        - AWS
        - Azure
        - AzureStack
        - IBMCloud
        - Installer
        - Metal
        - Nutanix
        - OpenStack
        - VMware
        - GCP

# remove to disable S3 uploads
# s3_bucket: rhcos-ci
# path: releases/4.11-devel

# clouds:
#   aws:
#     # Accounts to share newly created AMIs with
#     test_accounts:
#       - "013116697141"
#   azure:
#     test_resource_group: fedora-coreos-testing
#     test_storage_account: fedoracoreostesting
#     test_storage_container: fedora-coreos-testing-image-blobs
#   gcp:
#     bucket: fedora-coreos-cloud-image-uploads
